name: Auto Merge Pull Requests

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      # Debug: only run when there actually is a pull_request in the event payload
      - name: Debug PR context (safe)
        if: ${{ github.event.pull_request != null }}
        run: |
          echo "GITHUB_REPOSITORY=${{ github.repository }}"
          echo "EVENT_NAME=${{ github.event_name }}"
          echo "PULL_REQUEST_NUMBER=${{ github.event.pull_request.number }}"
          # Safely write the entire pull_request JSON into a file and print first 200 lines
          printf '%s\n' "${{ toJson(github.event.pull_request) }}" > pr_payload.json || true
          sed -n '1,200p' pr_payload.json || true

      # If there is no pull_request object (e.g., manual dispatch), skip the enable step.
      - name: Enable auto-merge for PR
        if: ${{ github.event.pull_request != null }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      # Helpful message when no PR present (won't run for PR events)
      - name: No PR present
        if: ${{ github.event.pull_request == null }}
        run: echo "No pull_request found in the event payload; nothing to do."
