name: Auto Merge Pull Requests

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      # Must checkout the repo so gh/git commands can run
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # fetch enough history/refs that gh can detect branches
          fetch-depth: 0

      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          merge-when-labeled: automerge
